name: Update deployment tag v2 - WIP
permissions:
  id-token: write
  contents: read
on:
  workflow_dispatch:
    inputs:
      tag:
        description: Which tag
        required: true
      name:
        description: Name of deployment
        required: true
jobs:
  update-deployment-tag:
    name: Update deployment tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v3

      - name: Setup inputs ðŸ“¥
        uses: simenandre/setup-inputs@v1
        id: inputs

      - name: Set summary ðŸ“ â€“ ${{ steps.inputs.outputs.name }} ðŸ‘‰ ${{ steps.inputs.outputs.tag }}
        run: |
          echo "**${{ steps.inputs.outputs.name }}** set to **${{ steps.inputs.outputs.tag }}**" >> $GITHUB_STEP_SUMMARY

      - name: Set config ðŸ”§
        uses: simenandre/pulumi-config@v2
        id: config
        env:
          GITHUB_TOKEN: ${{ secrets.BJERKBOT_GITHUB_TOKEN }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        with:
          stack-name: branches/branches-main/main
          key: ${{ steps.inputs.outputs.name }}:tag
          value: ${{ steps.inputs.outputs.tag }}

      - name: Get changelog from commit ðŸ“œ
        uses: simenandre/get-commit-changelog@v1
        id: changelog
        if: steps.config.outputs.key
        with:
          token: ${{ secrets.BJERKBOT_GITHUB_TOKEN }}
          repository: ${{ steps.inputs.outputs.repository }}
          base: ${{ fromJson(steps.config.outputs.key).value }}
          head: ${{ steps.inputs.outputs.tag }}

      - name: Create Pull Request ðŸŽ‰
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.BJERKBOT_GITHUB_TOKEN }}
          commit-message:
            bump ${{ steps.inputs.outputs.name }} to ${{
            steps.inputs.outputs.tag }}
          branch: bump-tag-${{ steps.inputs.outputs.name }}
          title:
            'chore: bump ${{ steps.inputs.outputs.name }} tag to `${{
            steps.inputs.outputs.tag }}`'
          body: |
            Automated tag change. ðŸŽ‰

            ${{ steps.changelog.outputs.changelog }}
